apiVersion: v1
kind: Service
metadata:
  labels:
    app: desk-service
  name: desk-service-expose
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: desk-service
  type: ClusterIP
